# backtest params keys
name = 'name'
lo_ticker = 'lo_ticker'
force_download = 'force_download'
quandl_ticker = 'quandl_ticker'
weighting = 'weighting'
vs_window = 'vs_window'
vs_chg_rule = 'vs_chg_rule'
vs_target_vol = 'vs_target_vol'
vs_cap = 'vs_cap'
vs_floor = 'vs_floor'
signal_type = 'signal_type'
signal_windows = 'signal_windows'
signal_to_position = 'signal_to_position'
signal_chg_rule = 'signal_chg_rule'
position_cap = 'position_cap'
position_floor = 'position_floor'
start_date = 'start_date'
end_date = 'end_date'
n_items = 'n_items'
slippage = 'slippage'
backtest_ccy = 'backtest_ccy'
price_source = 'price_source'

# backtest price sources
pcs_quandl_futures = 'pcs_quandl_futures'
pcs_quandl_generic = 'pcs_quandl_generic'
pcs_truefx = 'pcs_truefx'

# layers params values
equal_weight = 'equal_weight'
momentum = 'momentum'
linear = 'linear'

# futures info
full_name = 'full_name'
asset_class = 'asset_class'
start_from = 'start_from'
denominator = 'denominator'
tick_size = 'tick_size'
contract_ccy = 'contract_ccy'
roll_schedule = 'roll_schedule'
first_notice_date = 'first_notice_date'
last_trade_date = 'last_trade_date'

# MongoDB
quandl_contract = 'quandl_contract'
cash_returns = 'cash_returns'
fx_rates = 'fx_rates'
backtest = 'backtest'
