# backtest params keys
name = 'name'
lo_ticker = 'lo_ticker'
force_download = 'force_download'
quandl_ticker = 'quandl_ticker'
weighting = 'weighting'
vs_window = 'vs_window'
vs_chg_rule = 'vs_chg_rule'
vs_target_vol = 'vs_target_vol'
vs_cap = 'vs_cap'
vs_floor = 'vs_floor'
vs_method_params = 'vs_method_params'
vs_method = 'vs_method'
vs_ewm_com = 'vs_ewm_com'
vs_ewm_span = 'vs_ewm_span'
vs_ewm_halflife = 'vs_ewm_halflife'
vs_ewm_alpha = 'vs_ewm_alpha'
signal_type = 'signal_type'
signal_windows = 'signal_windows'
signal_to_position = 'signal_to_position'
signal_chg_rule = 'signal_chg_rule'
signal_method_params = 'signal_method_params'
signal_method = 'signal_method'
position_cap = 'position_cap'
position_floor = 'position_floor'
port_weight_chg_rule = 'port_weight_chg_rule'
start_date = 'start_date'
end_date = 'end_date'
n_items = 'n_items'
slippage = 'slippage'
backtest_ccy = 'backtest_ccy'
price_source = 'price_source'
nth_contract = 'nth_contract'
is_spliced = 'is_spliced'
splice_func = 'splice_func'
splice_es_and_sp = 'splice_es_and_sp'
splice_nq_and_nd = 'splice_nq_and_nd'
splice_ym_and_dj = 'splice_ym_and_dj'

# backtest price sources
pcs_quandl_futures = 'pcs_quandl_futures'
pcs_quandl_generic = 'pcs_quandl_generic'
pcs_truefx = 'pcs_truefx'

# layers params values
equal_weight = 'equal_weight'
vs_rolling = 'vs_rolling'
vs_ewm = 'vs_ewm'
signal_trend_ma_xover = 'signal_trend_ma_xover'
momentum = 'momentum'
linear = 'linear'

# futures info
full_name = 'full_name'
asset_class = 'asset_class'
start_from = 'start_from'
denominator = 'denominator'
tick_size = 'tick_size'
contract_ccy = 'contract_ccy'
roll_schedule = 'roll_schedule'
first_notice_date = 'first_notice_date'
last_trade_date = 'last_trade_date'

# MongoDB
quandl_contract = 'quandl_contract'
cash_returns = 'cash_returns'
fx_rates = 'fx_rates'
backtest = 'backtest'
